/*
 * JS for body generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

body_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_1': 'body_mobilelabel_1',
        'list1': 'body_list1',
        'mobileselectmenuitem_3': 'body_mobileselectmenuitem_3',
        'mobilelabel_4': 'body_mobilelabel_4',
        'list2': 'body_list2',
        'mobileselectmenuitem_6': 'body_mobileselectmenuitem_6',
        'mobilebutton_7': 'body_mobilebutton_7'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'body';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    body_beforeshow = function() {
        Appery.CurrentScreen = "body";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_9302_onLoad = body_onLoad = function() {
        screen_9302_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        body_deviceEvents();
        body_windowEvents();
        screen_9302_elementsEvents();
    }

    // screen window events
    screen_9302_windowEvents = body_windowEvents = function() {

        $('#body').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    body_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_9302_elementsExtraJS = body_elementsExtraJS = function() {
        // screen (body) extra code

        /* list1 */

        $("#body_list1").parent().find("a.ui-btn").attr("tabindex", "1");

        /* list2 */

        $("#body_list2").parent().find("a.ui-btn").attr("tabindex", "2");

    }

    // screen elements handler
    screen_9302_elementsEvents = body_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#body_mobilecontainer [name="list1"]').die().live({
            change: function() {
                var selectedValue = this.value;
                var data = {
                    'Chest': ['Orange', 'Apple', 'Banana'],
                    'Head': ['Under Construction', 'Under Construction']
                };

                var dropDown = $('[name=list2]');
                dropDown.html('');
                var newData = data[selectedValue];
                for (i = 0; i < newData.length; i++) {
                    dropDown.append('<option value=​"' + newData[i] + i + '">​' + newData[i] + '</option>');
                }
                dropDown.selectmenu('refresh');
            },
        });

        $('#body_mobilecontainer [name="mobilebutton_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('tests', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#body").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        body_beforeshow();
    });

    if (runBeforeShow) {
        body_beforeshow();
    } else {
        body_onLoad();
    }

}

$("#body").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    body_js();
});