/*
 * JS for CarePass_BodyMeasurementsType_Filter generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

CarePass_BodyMeasurementsType_Filter_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar2_6': 'CarePass_BodyMeasurementsType_Filter_mobilenavbar2_6',
        'mobilenavbaritem4_7': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_7',
        'mobilenavbaritem4_8': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_8',
        'mobilenavbaritem4_9': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_9',
        'mobilelabel1_10': 'CarePass_BodyMeasurementsType_Filter_mobilelabel1_10',
        'formDate': 'CarePass_BodyMeasurementsType_Filter_formDate',
        'mobilelabel1_12': 'CarePass_BodyMeasurementsType_Filter_mobilelabel1_12',
        'toDate': 'CarePass_BodyMeasurementsType_Filter_toDate',
        'Filter': 'CarePass_BodyMeasurementsType_Filter_Filter',
        'simpleMeasurement': 'CarePass_BodyMeasurementsType_Filter_simpleMeasurement',
        'mobilecollapsblockheader1_16': 'CarePass_BodyMeasurementsType_Filter_mobilecollapsblockheader1_16',
        'mobilecollapsblockcontent1_17': 'CarePass_BodyMeasurementsType_Filter_mobilecollapsblockcontent1_17',
        'simpleMeasurementGrid': 'CarePass_BodyMeasurementsType_Filter_simpleMeasurementGrid',
        'mobilegridcell_19': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_19',
        'mType': 'CarePass_BodyMeasurementsType_Filter_mType',
        'mobilegridcell_20': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_20',
        'mValue': 'CarePass_BodyMeasurementsType_Filter_mValue',
        'mUnit': 'CarePass_BodyMeasurementsType_Filter_mUnit',
        'mobilegridcell_21': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_21',
        'mobilelabel1_28': 'CarePass_BodyMeasurementsType_Filter_mobilelabel1_28',
        'mobilegridcell_22': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_22',
        'mDate': 'CarePass_BodyMeasurementsType_Filter_mDate',
        'mobilegridcell_23': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_23',
        'mobilelabel1_29': 'CarePass_BodyMeasurementsType_Filter_mobilelabel1_29',
        'mobilegridcell_24': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_24',
        'mNote': 'CarePass_BodyMeasurementsType_Filter_mNote',
        'mobilegridcell_30': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_30',
        'mID': 'CarePass_BodyMeasurementsType_Filter_mID',
        'mobilegridcell_31': 'CarePass_BodyMeasurementsType_Filter_mobilegridcell_31',
        'showMore': 'CarePass_BodyMeasurementsType_Filter_showMore',
        'measurements_filter_error': 'CarePass_BodyMeasurementsType_Filter_measurements_filter_error',
        'mobilenavbar2_2': 'CarePass_BodyMeasurementsType_Filter_mobilenavbar2_2',
        'mobilenavbaritem4_3': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_3',
        'mobilenavbaritem4_4': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_4',
        'mobilenavbaritem4_5': 'CarePass_BodyMeasurementsType_Filter_mobilenavbaritem4_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CarePass_BodyMeasurementsType_Filter';

    /*
     * Nonvisual components
     */
    var datasources = [];

    LastMeasurement = new Appery.DataSource(CarePass_BodyMeasurements_Latest_GET, {
        'onComplete': function(jqXHR, textStatus) {
            Helper.hideOverview();

            $t.refreshScreenFormElements("CarePass_BodyMeasurementsType_Filter");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'simpleMeasurement',
            'SET': [{
                'PATH': ['measurementType'],
                'ID': 'mType',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return value + ":";
                }
            }, {
                'PATH': ['numericValue'],
                'ID': 'mValue',
                'ATTR': '@'
            }, {
                'PATH': ['valueUnit'],
                'ID': 'mUnit',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'mDate',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }, {
                'PATH': ['notes'],
                'ID': 'mNote',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return value || "-"
                }
            }, {
                'PATH': ['id'],
                'ID': 'mID',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'mobilecollapsblockheader1_16',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }]
        }],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ID': '___local_storage___',
            'ATTR': 'token',
            'TRANSFORMATION': function(value) {
                return "Bearer " + value;
            }
        }, {
            'PATH': ['Accept'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['measurementType'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'measurement'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.carepass.com/user-directory-api/users/currentUser/health/body/measurements/latest'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1396056549918'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2400671'
        }]
    });

    datasources.push(LastMeasurement);

    FilterMeasurement = new Appery.DataSource(CarePass_BodyMeasurements_Filter_GET, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CarePass_BodyMeasurementsType_Filter");
        },
        'onSuccess': function(data) {
            Tiggzi("measurements_filter_error").hide();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Tiggzi("measurements_filter_error").show();
            $(".simpleMeasurement").css("display", "none");
        },
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'simpleMeasurement',
            'SET': [{
                'PATH': ['measurementType'],
                'ID': 'mType',
                'ATTR': '@'
            }, {
                'PATH': ['numericValue'],
                'ID': 'mValue',
                'ATTR': '@'
            }, {
                'PATH': ['valueUnit'],
                'ID': 'mUnit',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'mDate',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }, {
                'PATH': ['notes'],
                'ID': 'mNote',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return value || "-"
                }
            }, {
                'PATH': ['id'],
                'ID': 'mID',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'mobilecollapsblockheader1_16',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }]
        }],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ID': '___local_storage___',
            'ATTR': 'token',
            'TRANSFORMATION': function(value) {
                return "Bearer " + value;
            }
        }, {
            'PATH': ['Accept'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['fromDate'],
            'TYPE': 'STRING',
            'ID': 'formDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['toDate'],
            'TYPE': 'STRING',
            'ID': 'toDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['measurementType'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'measurement'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.carepass.com/user-directory-api/users/currentUser/health/body/measurements'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1396056549927'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2400672'
        }]
    });

    datasources.push(FilterMeasurement);

    /*
     * Events and handlers
     */

    // Before Show
    CarePass_BodyMeasurementsType_Filter_beforeshow = function() {
        Appery.CurrentScreen = "CarePass_BodyMeasurementsType_Filter";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_D930_onLoad = CarePass_BodyMeasurementsType_Filter_onLoad = function() {
        screen_D930_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        CarePass_BodyMeasurementsType_Filter_deviceEvents();
        CarePass_BodyMeasurementsType_Filter_windowEvents();
        screen_D930_elementsEvents();
    }

    // screen window events
    screen_D930_windowEvents = CarePass_BodyMeasurementsType_Filter_windowEvents = function() {

        $('#CarePass_BodyMeasurementsType_Filter').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#CarePass_BodyMeasurementsType_Filter').bind({
            pageshow: function() {
                Helper.showOverview();
                Helper.fixFooterNavbar(this);
                Helper.setCurrentDateBefore("formDate");
                Helper.setCurrentDate("toDate");
                try {
                    LastMeasurement.execute({})
                } catch (ex) {
                    console.log(ex.name + '  ' + ex.message);
                    hideSpinner();
                };
            },
        });

    }

    // device events
    CarePass_BodyMeasurementsType_Filter_deviceEvents = function() {

        document.addEventListener("deviceready", function() {
            $(document).unbind('offline ').bind({
                "offline": function() {
                    Appery.navigateTo('CarePass_ErrorPopUp', {
                        transition: 'pop'
                    });
                },
            });

        });
    }

    // screen elements extra js
    screen_D930_elementsExtraJS = CarePass_BodyMeasurementsType_Filter_elementsExtraJS = function() {
        // screen (CarePass_BodyMeasurementsType_Filter) extra code

        /* formDate */

        CarePass_BodyMeasurementsType_Filter_formDate_selector = "#CarePass_BodyMeasurementsType_Filter_formDate";
        CarePass_BodyMeasurementsType_Filter_formDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_BodyMeasurementsType_Filter_formDate_dataPickerOptions.defaultDate = new Date("02/26/2013");

        Appery.__registerComponent('formDate', new Appery.ApperyMobileDatePickerComponent("CarePass_BodyMeasurementsType_Filter_formDate", CarePass_BodyMeasurementsType_Filter_formDate_dataPickerOptions));

        /* toDate */

        CarePass_BodyMeasurementsType_Filter_toDate_selector = "#CarePass_BodyMeasurementsType_Filter_toDate";
        CarePass_BodyMeasurementsType_Filter_toDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_BodyMeasurementsType_Filter_toDate_dataPickerOptions.defaultDate = new Date("02/26/2013");

        Appery.__registerComponent('toDate', new Appery.ApperyMobileDatePickerComponent("CarePass_BodyMeasurementsType_Filter_toDate", CarePass_BodyMeasurementsType_Filter_toDate_dataPickerOptions));

        /* simpleMeasurement */

        $("#CarePass_BodyMeasurementsType_Filter_simpleMeasurement .ui-collapsible-heading-toggle").attr("tabindex", "4");

    }

    // screen elements handler
    screen_D930_elementsEvents = CarePass_BodyMeasurementsType_Filter_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CarePass_BodyMeasurementsType_Filter_mobileheader [name="mobilenavbaritem4_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurementsType_Filter_mobileheader [name="mobilenavbaritem4_8"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurementsType_Filter_mobileheader [name="mobilenavbaritem4_9"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_TimeLine', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_BodyMeasurementsType_Filter_mobilecontainer [name="Filter"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        FilterMeasurement.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };

                }
            },
        });

        $('#CarePass_BodyMeasurementsType_Filter_mobilecontainer [name="showMore"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    setVar_('measurementID', 'CarePass_BodyMeasurementsType_Filter_mID', 'text', '', this);
                    localStorage.setItem('message', 'Measurement details');
                    Appery.navigateTo('CarePass_BodyMeasurements_Single', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_BodyMeasurementsType_Filter_mobilefooter1 [name="mobilenavbaritem4_3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_All', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurementsType_Filter_mobilefooter1 [name="mobilenavbaritem4_4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurementsType_Filter_mobilefooter1 [name="mobilenavbaritem4_5"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_Filter', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#CarePass_BodyMeasurementsType_Filter").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CarePass_BodyMeasurementsType_Filter_beforeshow();
    });

    if (runBeforeShow) {
        CarePass_BodyMeasurementsType_Filter_beforeshow();
    } else {
        CarePass_BodyMeasurementsType_Filter_onLoad();
    }

}

$("#CarePass_BodyMeasurementsType_Filter").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CarePass_BodyMeasurementsType_Filter_js();
});