/*
 * JS for CarePass_Fitness_Activity_TimeLine generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

CarePass_Fitness_Activity_TimeLine_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar2_6': 'CarePass_Fitness_Activity_TimeLine_mobilenavbar2_6',
        'mobilenavbaritem4_7': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_7',
        'mobilenavbaritem4_8': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_8',
        'mobilenavbaritem4_9': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_9',
        'mobilelabel1_10': 'CarePass_Fitness_Activity_TimeLine_mobilelabel1_10',
        'gType': 'CarePass_Fitness_Activity_TimeLine_gType',
        'mobileselectmenuitem1': 'CarePass_Fitness_Activity_TimeLine_mobileselectmenuitem1',
        'mobilelabel1_15': 'CarePass_Fitness_Activity_TimeLine_mobilelabel1_15',
        'gFromDate': 'CarePass_Fitness_Activity_TimeLine_gFromDate',
        'mobilelabel1_17': 'CarePass_Fitness_Activity_TimeLine_mobilelabel1_17',
        'gToDate': 'CarePass_Fitness_Activity_TimeLine_gToDate',
        'mobilebutton1_14': 'CarePass_Fitness_Activity_TimeLine_mobilebutton1_14',
        'timeline_filter_error': 'CarePass_Fitness_Activity_TimeLine_timeline_filter_error',
        'mobilenavbar2_2': 'CarePass_Fitness_Activity_TimeLine_mobilenavbar2_2',
        'mobilenavbaritem4_3': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_3',
        'mobilenavbaritem4_4': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_4',
        'mobilenavbaritem4_5': 'CarePass_Fitness_Activity_TimeLine_mobilenavbaritem4_5'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CarePass_Fitness_Activity_TimeLine';

    /*
     * Nonvisual components
     */
    var datasources = [];

    GraphicData = new Appery.DataSource(CarePass_BodyMeasurements_Filter_GET, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CarePass_Fitness_Activity_TimeLine");
        },
        'onSuccess': function(data) {
            Tiggzi("timeline_filter_error").hide();
            localStorage.setItem("graphicData", JSON.stringify(data));
            Appery.navigateTo('CarePass_Chart', {
                reverse: false
            });
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Tiggzi("timeline_filter_error").show();
        },
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ID': '___local_storage___',
            'ATTR': 'token',
            'TRANSFORMATION': function(value) {
                return "Bearer " + value;
            }
        }, {
            'PATH': ['Accept'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['fromDate'],
            'TYPE': 'STRING',
            'ID': 'gFromDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['toDate'],
            'TYPE': 'STRING',
            'ID': 'gToDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['measurementType'],
            'TYPE': 'STRING',
            'ID': 'gType',
            'ATTR': 'value'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'https://api.carepass.com/user-directory-api/users/currentUser/health/body/measurements'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1396056550036'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2400672'
        }]
    });

    datasources.push(GraphicData);

    /*
     * Events and handlers
     */

    // Before Show
    CarePass_Fitness_Activity_TimeLine_beforeshow = function() {
        Appery.CurrentScreen = "CarePass_Fitness_Activity_TimeLine";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_995A_onLoad = CarePass_Fitness_Activity_TimeLine_onLoad = function() {
        screen_995A_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        CarePass_Fitness_Activity_TimeLine_deviceEvents();
        CarePass_Fitness_Activity_TimeLine_windowEvents();
        screen_995A_elementsEvents();
    }

    // screen window events
    screen_995A_windowEvents = CarePass_Fitness_Activity_TimeLine_windowEvents = function() {

        $('#CarePass_Fitness_Activity_TimeLine').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#CarePass_Fitness_Activity_TimeLine').bind({
            pageshow: function() {
                Helper.fixFooterNavbar(this);
            },
        });

    }

    // device events
    CarePass_Fitness_Activity_TimeLine_deviceEvents = function() {

        document.addEventListener("deviceready", function() {
            $(document).unbind('offline ').bind({
                "offline": function() {
                    Appery.navigateTo('CarePass_ErrorPopUp', {
                        transition: 'pop'
                    });
                },
            });

        });
    }

    // screen elements extra js
    screen_995A_elementsExtraJS = CarePass_Fitness_Activity_TimeLine_elementsExtraJS = function() {
        // screen (CarePass_Fitness_Activity_TimeLine) extra code

        /* gType */

        $("#CarePass_Fitness_Activity_TimeLine_gType").parent().find("a.ui-btn").attr("tabindex", "1");

        /* gFromDate */

        CarePass_Fitness_Activity_TimeLine_gFromDate_selector = "#CarePass_Fitness_Activity_TimeLine_gFromDate";
        CarePass_Fitness_Activity_TimeLine_gFromDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_Fitness_Activity_TimeLine_gFromDate_dataPickerOptions.defaultDate = new Date("02/01/2013");

        Appery.__registerComponent('gFromDate', new Appery.ApperyMobileDatePickerComponent("CarePass_Fitness_Activity_TimeLine_gFromDate", CarePass_Fitness_Activity_TimeLine_gFromDate_dataPickerOptions));

        /* gToDate */

        CarePass_Fitness_Activity_TimeLine_gToDate_selector = "#CarePass_Fitness_Activity_TimeLine_gToDate";
        CarePass_Fitness_Activity_TimeLine_gToDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_Fitness_Activity_TimeLine_gToDate_dataPickerOptions.defaultDate = new Date("03/01/2013");

        Appery.__registerComponent('gToDate', new Appery.ApperyMobileDatePickerComponent("CarePass_Fitness_Activity_TimeLine_gToDate", CarePass_Fitness_Activity_TimeLine_gToDate_dataPickerOptions));

    }

    // screen elements handler
    screen_995A_elementsEvents = CarePass_Fitness_Activity_TimeLine_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CarePass_Fitness_Activity_TimeLine_mobileheader [name="mobilenavbaritem4_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_TimeLine_mobileheader [name="mobilenavbaritem4_8"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements_New', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_Fitness_Activity_TimeLine_mobilecontainer [name="mobilebutton1_14"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        GraphicData.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };

                }
            },
        });

        $('#CarePass_Fitness_Activity_TimeLine_mobilefooter1 [name="mobilenavbaritem4_3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_All', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_TimeLine_mobilefooter1 [name="mobilenavbaritem4_4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_TimeLine_mobilefooter1 [name="mobilenavbaritem4_5"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_Filter', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#CarePass_Fitness_Activity_TimeLine").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CarePass_Fitness_Activity_TimeLine_beforeshow();
    });

    if (runBeforeShow) {
        CarePass_Fitness_Activity_TimeLine_beforeshow();
    } else {
        CarePass_Fitness_Activity_TimeLine_onLoad();
    }

}

$("#CarePass_Fitness_Activity_TimeLine").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CarePass_Fitness_Activity_TimeLine_js();
});