/*
 * JS for CarePass_Fitness_Activity_Filter generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

CarePass_Fitness_Activity_Filter_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar2_10': 'CarePass_Fitness_Activity_Filter_mobilenavbar2_10',
        'mobilenavbaritem4_11': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_11',
        'mobilenavbaritem4_12': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_12',
        'mobilenavbaritem4_13': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_13',
        'mobilelabel1_22': 'CarePass_Fitness_Activity_Filter_mobilelabel1_22',
        'formDate': 'CarePass_Fitness_Activity_Filter_formDate',
        'mobilelabel1_23': 'CarePass_Fitness_Activity_Filter_mobilelabel1_23',
        'toDate': 'CarePass_Fitness_Activity_Filter_toDate',
        'mobilelabel1_26': 'CarePass_Fitness_Activity_Filter_mobilelabel1_26',
        'activityType': 'CarePass_Fitness_Activity_Filter_activityType',
        'mobileselectmenuitem1': 'CarePass_Fitness_Activity_Filter_mobileselectmenuitem1',
        'filterBtn': 'CarePass_Fitness_Activity_Filter_filterBtn',
        'simpleActivity': 'CarePass_Fitness_Activity_Filter_simpleActivity',
        'simpleActivityTitle': 'CarePass_Fitness_Activity_Filter_simpleActivityTitle',
        'mobilecollapsblockcontent1_29': 'CarePass_Fitness_Activity_Filter_mobilecollapsblockcontent1_29',
        'mobilegrid_30': 'CarePass_Fitness_Activity_Filter_mobilegrid_30',
        'mobilegridcell_31': 'CarePass_Fitness_Activity_Filter_mobilegridcell_31',
        'mobilelabel1_41': 'CarePass_Fitness_Activity_Filter_mobilelabel1_41',
        'mobilegridcell_32': 'CarePass_Fitness_Activity_Filter_mobilegridcell_32',
        'simpleActuvityType': 'CarePass_Fitness_Activity_Filter_simpleActuvityType',
        'mobilegridcell_33': 'CarePass_Fitness_Activity_Filter_mobilegridcell_33',
        'mobilelabel1_42': 'CarePass_Fitness_Activity_Filter_mobilelabel1_42',
        'mobilegridcell_34': 'CarePass_Fitness_Activity_Filter_mobilegridcell_34',
        'simpleActuvityDate': 'CarePass_Fitness_Activity_Filter_simpleActuvityDate',
        'mobilegridcell_35': 'CarePass_Fitness_Activity_Filter_mobilegridcell_35',
        'mobilelabel1_43': 'CarePass_Fitness_Activity_Filter_mobilelabel1_43',
        'mobilegridcell_36': 'CarePass_Fitness_Activity_Filter_mobilegridcell_36',
        'simpleActuvityCalories': 'CarePass_Fitness_Activity_Filter_simpleActuvityCalories',
        'mobilegridcell_37': 'CarePass_Fitness_Activity_Filter_mobilegridcell_37',
        'mobilelabel1_44': 'CarePass_Fitness_Activity_Filter_mobilelabel1_44',
        'mobilegridcell_38': 'CarePass_Fitness_Activity_Filter_mobilegridcell_38',
        'simpleActuvityDistance': 'CarePass_Fitness_Activity_Filter_simpleActuvityDistance',
        'simpleActuvityDistanceUnits': 'CarePass_Fitness_Activity_Filter_simpleActuvityDistanceUnits',
        'mobilegridcell_39': 'CarePass_Fitness_Activity_Filter_mobilegridcell_39',
        'mobilelabel1_45': 'CarePass_Fitness_Activity_Filter_mobilelabel1_45',
        'mobilegridcell_40': 'CarePass_Fitness_Activity_Filter_mobilegridcell_40',
        'simpleActuvityDuration': 'CarePass_Fitness_Activity_Filter_simpleActuvityDuration',
        'mobilegridcell_46': 'CarePass_Fitness_Activity_Filter_mobilegridcell_46',
        'activityID': 'CarePass_Fitness_Activity_Filter_activityID',
        'mobilegridcell_47': 'CarePass_Fitness_Activity_Filter_mobilegridcell_47',
        'showMore': 'CarePass_Fitness_Activity_Filter_showMore',
        'filter_error': 'CarePass_Fitness_Activity_Filter_filter_error',
        'mobilenavbar2_6': 'CarePass_Fitness_Activity_Filter_mobilenavbar2_6',
        'mobilenavbaritem4_7': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_7',
        'mobilenavbaritem4_8': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_8',
        'mobilenavbaritem4_9': 'CarePass_Fitness_Activity_Filter_mobilenavbaritem4_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CarePass_Fitness_Activity_Filter';

    /*
     * Nonvisual components
     */
    var datasources = [];

    Filter_Activity = new Appery.DataSource(CarePass_Fitness_ActivitiesFilter_GET, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CarePass_Fitness_Activity_Filter");
        },
        'onSuccess': function(data) {
            Tiggzi("filter_error").hide();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Tiggzi("filter_error").show();
            $(".simpleActivity").css("display", "none");
        },
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'simpleActivity',
            'SET': [{
                'PATH': ['id'],
                'ID': 'activityID',
                'ATTR': '@'
            }, {
                'PATH': ['type'],
                'ID': 'simpleActuvityType',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'simpleActuvityDate',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }, {
                'PATH': ['caloriesBurned'],
                'ID': 'simpleActuvityCalories',
                'ATTR': '@'
            }, {
                'PATH': ['distance'],
                'ID': 'simpleActuvityDistance',
                'ATTR': '@'
            }, {
                'PATH': ['duration'],
                'ID': 'simpleActuvityDuration',
                'ATTR': '@'
            }, {
                'PATH': ['distanceUnit'],
                'ID': 'simpleActuvityDistanceUnits',
                'ATTR': '@'
            }, {
                'PATH': ['date'],
                'ID': 'simpleActivityTitle',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    return Helper.parseDate(value);
                }
            }]
        }],
        'requestMapping': [{
            'PATH': ['Authorization'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ID': '___local_storage___',
            'ATTR': 'token',
            'TRANSFORMATION': function(value) {
                return "Bearer " + value;
            }
        }, {
            'PATH': ['Accept'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': 'application/json'
        }, {
            'PATH': ['fromDate'],
            'TYPE': 'STRING',
            'ID': 'formDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['toDate'],
            'TYPE': 'STRING',
            'ID': 'toDate',
            'ATTR': 'defaultDateValue'
        }, {
            'PATH': ['type'],
            'TYPE': 'STRING',
            'ID': 'activityType',
            'ATTR': 'value'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': ' https://api.carepass.com/user-directory-api/users/currentUser/fitness/activities'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1396056549621'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2400666'
        }]
    });

    datasources.push(Filter_Activity);

    /*
     * Events and handlers
     */

    // Before Show
    CarePass_Fitness_Activity_Filter_beforeshow = function() {
        Appery.CurrentScreen = "CarePass_Fitness_Activity_Filter";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_5B3F_onLoad = CarePass_Fitness_Activity_Filter_onLoad = function() {
        screen_5B3F_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        CarePass_Fitness_Activity_Filter_deviceEvents();
        CarePass_Fitness_Activity_Filter_windowEvents();
        screen_5B3F_elementsEvents();
    }

    // screen window events
    screen_5B3F_windowEvents = CarePass_Fitness_Activity_Filter_windowEvents = function() {

        $('#CarePass_Fitness_Activity_Filter').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#CarePass_Fitness_Activity_Filter').bind({
            pageshow: function() {
                Helper.fixFooterNavbar(this);
                Helper.setCurrentDateBefore("formDate");
                Helper.setCurrentDate("toDate");
            },
        });

    }

    // device events
    CarePass_Fitness_Activity_Filter_deviceEvents = function() {

        document.addEventListener("deviceready", function() {
            $(document).unbind('offline ').bind({
                "offline": function() {
                    Appery.navigateTo('CarePass_ErrorPopUp', {
                        transition: 'pop'
                    });
                },
            });

        });
    }

    // screen elements extra js
    screen_5B3F_elementsExtraJS = CarePass_Fitness_Activity_Filter_elementsExtraJS = function() {
        // screen (CarePass_Fitness_Activity_Filter) extra code

        /* formDate */

        CarePass_Fitness_Activity_Filter_formDate_selector = "#CarePass_Fitness_Activity_Filter_formDate";
        CarePass_Fitness_Activity_Filter_formDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_Fitness_Activity_Filter_formDate_dataPickerOptions.defaultDate = new Date("02/22/2013");

        Appery.__registerComponent('formDate', new Appery.ApperyMobileDatePickerComponent("CarePass_Fitness_Activity_Filter_formDate", CarePass_Fitness_Activity_Filter_formDate_dataPickerOptions));

        /* toDate */

        CarePass_Fitness_Activity_Filter_toDate_selector = "#CarePass_Fitness_Activity_Filter_toDate";
        CarePass_Fitness_Activity_Filter_toDate_dataPickerOptions = {
            dateFormat: "yy-mm-dd",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        CarePass_Fitness_Activity_Filter_toDate_dataPickerOptions.defaultDate = new Date("02/22/2013");

        Appery.__registerComponent('toDate', new Appery.ApperyMobileDatePickerComponent("CarePass_Fitness_Activity_Filter_toDate", CarePass_Fitness_Activity_Filter_toDate_dataPickerOptions));

        /* activityType */

        $("#CarePass_Fitness_Activity_Filter_activityType").parent().find("a.ui-btn").attr("tabindex", "1");

        /* simpleActivity */

        $("#CarePass_Fitness_Activity_Filter_simpleActivity .ui-collapsible-heading-toggle").attr("tabindex", "5");

    }

    // screen elements handler
    screen_5B3F_elementsEvents = CarePass_Fitness_Activity_Filter_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CarePass_Fitness_Activity_Filter_mobileheader [name="mobilenavbaritem4_11"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_Filter_mobileheader [name="mobilenavbaritem4_12"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_Filter_mobileheader [name="mobilenavbaritem4_13"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_TimeLine', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_Fitness_Activity_Filter_mobilecontainer [name="filterBtn"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        Filter_Activity.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };

                }
            },
        });

        $('#CarePass_Fitness_Activity_Filter_mobilecontainer [name="showMore"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    setVar_('activityID', 'CarePass_Fitness_Activity_Filter_activityID', 'text', '', this);
                    localStorage.setItem('message', 'Activity details');
                    Appery.navigateTo('CarePass_Fitness_Activity_Single', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_Fitness_Activity_Filter_mobilefooter1 [name="mobilenavbaritem4_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_All', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_Fitness_Activity_Filter_mobilefooter1 [name="mobilenavbaritem4_8"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_New', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#CarePass_Fitness_Activity_Filter").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CarePass_Fitness_Activity_Filter_beforeshow();
    });

    if (runBeforeShow) {
        CarePass_Fitness_Activity_Filter_beforeshow();
    } else {
        CarePass_Fitness_Activity_Filter_onLoad();
    }

}

$("#CarePass_Fitness_Activity_Filter").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CarePass_Fitness_Activity_Filter_js();
});