/*
 * JS for CarePass_BodyMeasurements generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

CarePass_BodyMeasurements_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar2_10': 'CarePass_BodyMeasurements_mobilenavbar2_10',
        'mobilenavbaritem4_11': 'CarePass_BodyMeasurements_mobilenavbaritem4_11',
        'mobilenavbaritem4_12': 'CarePass_BodyMeasurements_mobilenavbaritem4_12',
        'mobilenavbaritem4_13': 'CarePass_BodyMeasurements_mobilenavbaritem4_13',
        'mobilecollapsblock1_24': 'CarePass_BodyMeasurements_mobilecollapsblock1_24',
        'mobilecollapsblockheader1_25': 'CarePass_BodyMeasurements_mobilecollapsblockheader1_25',
        'mobilecollapsblockcontent1_26': 'CarePass_BodyMeasurements_mobilecollapsblockcontent1_26',
        'ExternalMeasurements': 'CarePass_BodyMeasurements_ExternalMeasurements',
        'mobilelistitem1_31': 'CarePass_BodyMeasurements_mobilelistitem1_31',
        'mobilelistitembtn1_32': 'CarePass_BodyMeasurements_mobilelistitembtn1_32',
        'mobilelistitem1_33': 'CarePass_BodyMeasurements_mobilelistitem1_33',
        'mobilelistitembtn1_34': 'CarePass_BodyMeasurements_mobilelistitembtn1_34',
        'mobilelistitem1_35': 'CarePass_BodyMeasurements_mobilelistitem1_35',
        'mobilelistitembtn1_36': 'CarePass_BodyMeasurements_mobilelistitembtn1_36',
        'mobilelistitem1_37': 'CarePass_BodyMeasurements_mobilelistitem1_37',
        'mobilelistitembtn1_38': 'CarePass_BodyMeasurements_mobilelistitembtn1_38',
        'mobilelistitem1_39': 'CarePass_BodyMeasurements_mobilelistitem1_39',
        'mobilelistitembtn1_40': 'CarePass_BodyMeasurements_mobilelistitembtn1_40',
        'mobilelistitem1_41': 'CarePass_BodyMeasurements_mobilelistitem1_41',
        'mobilelistitembtn1_42': 'CarePass_BodyMeasurements_mobilelistitembtn1_42',
        'mobilelistitem1_43': 'CarePass_BodyMeasurements_mobilelistitem1_43',
        'mobilelistitembtn1_44': 'CarePass_BodyMeasurements_mobilelistitembtn1_44',
        'mobilelistitem1_45': 'CarePass_BodyMeasurements_mobilelistitem1_45',
        'mobilelistitembtn1_46': 'CarePass_BodyMeasurements_mobilelistitembtn1_46',
        'mobilelistitem1_47': 'CarePass_BodyMeasurements_mobilelistitem1_47',
        'mobilelistitembtn1_48': 'CarePass_BodyMeasurements_mobilelistitembtn1_48',
        'mobilelistitem1_49': 'CarePass_BodyMeasurements_mobilelistitem1_49',
        'mobilelistitembtn1_50': 'CarePass_BodyMeasurements_mobilelistitembtn1_50',
        'mobilecollapsblock1_27': 'CarePass_BodyMeasurements_mobilecollapsblock1_27',
        'mobilecollapsblockheader1_28': 'CarePass_BodyMeasurements_mobilecollapsblockheader1_28',
        'mobilecollapsblockcontent1_29': 'CarePass_BodyMeasurements_mobilecollapsblockcontent1_29',
        'InternalMeasurements': 'CarePass_BodyMeasurements_InternalMeasurements',
        'mobilelistitem1_52': 'CarePass_BodyMeasurements_mobilelistitem1_52',
        'mobilelistitembtn1_53': 'CarePass_BodyMeasurements_mobilelistitembtn1_53',
        'mobilelistitem1_54': 'CarePass_BodyMeasurements_mobilelistitem1_54',
        'mobilelistitembtn1_55': 'CarePass_BodyMeasurements_mobilelistitembtn1_55',
        'mobilelistitem1_56': 'CarePass_BodyMeasurements_mobilelistitem1_56',
        'mobilelistitembtn1_57': 'CarePass_BodyMeasurements_mobilelistitembtn1_57',
        'mobilelistitem1_58': 'CarePass_BodyMeasurements_mobilelistitem1_58',
        'mobilelistitembtn1_59': 'CarePass_BodyMeasurements_mobilelistitembtn1_59',
        'mobilelistitem1_60': 'CarePass_BodyMeasurements_mobilelistitem1_60',
        'mobilelistitembtn1_61': 'CarePass_BodyMeasurements_mobilelistitembtn1_61',
        'mobilelistitem1_62': 'CarePass_BodyMeasurements_mobilelistitem1_62',
        'mobilelistitembtn1_63': 'CarePass_BodyMeasurements_mobilelistitembtn1_63',
        'mobilelistitem1_64': 'CarePass_BodyMeasurements_mobilelistitem1_64',
        'mobilelistitembtn1_65': 'CarePass_BodyMeasurements_mobilelistitembtn1_65',
        'mobilelistitem1_66': 'CarePass_BodyMeasurements_mobilelistitem1_66',
        'mobilelistitembtn1_67': 'CarePass_BodyMeasurements_mobilelistitembtn1_67',
        'mobilelistitem1_68': 'CarePass_BodyMeasurements_mobilelistitem1_68',
        'mobilelistitembtn1_69': 'CarePass_BodyMeasurements_mobilelistitembtn1_69',
        'mobilelistitem1_70': 'CarePass_BodyMeasurements_mobilelistitem1_70',
        'mobilelistitembtn1_71': 'CarePass_BodyMeasurements_mobilelistitembtn1_71',
        'mobilelistitem1_72': 'CarePass_BodyMeasurements_mobilelistitem1_72',
        'mobilelistitembtn1_73': 'CarePass_BodyMeasurements_mobilelistitembtn1_73',
        'mobilelistitem1_74': 'CarePass_BodyMeasurements_mobilelistitem1_74',
        'mobilelistitembtn1_75': 'CarePass_BodyMeasurements_mobilelistitembtn1_75',
        'mobilelistitem1_76': 'CarePass_BodyMeasurements_mobilelistitem1_76',
        'mobilelistitembtn1_77': 'CarePass_BodyMeasurements_mobilelistitembtn1_77',
        'mobilenavbar2_6': 'CarePass_BodyMeasurements_mobilenavbar2_6',
        'mobilenavbaritem4_7': 'CarePass_BodyMeasurements_mobilenavbaritem4_7',
        'mobilenavbaritem4_8': 'CarePass_BodyMeasurements_mobilenavbaritem4_8',
        'mobilenavbaritem4_9': 'CarePass_BodyMeasurements_mobilenavbaritem4_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CarePass_BodyMeasurements';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    CarePass_BodyMeasurements_beforeshow = function() {
        Appery.CurrentScreen = "CarePass_BodyMeasurements";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_DACB_onLoad = CarePass_BodyMeasurements_onLoad = function() {
        screen_DACB_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        CarePass_BodyMeasurements_deviceEvents();
        CarePass_BodyMeasurements_windowEvents();
        screen_DACB_elementsEvents();
    }

    // screen window events
    screen_DACB_windowEvents = CarePass_BodyMeasurements_windowEvents = function() {

        $('#CarePass_BodyMeasurements').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#CarePass_BodyMeasurements').bind({
            pageshow: function() {
                Helper.fixFooterNavbar(this);
            },
        });

    }

    // device events
    CarePass_BodyMeasurements_deviceEvents = function() {

        document.addEventListener("deviceready", function() {
            $(document).unbind('offline ').bind({
                "offline": function() {
                    Appery.navigateTo('CarePass_ErrorPopUp', {
                        transition: 'pop'
                    });
                },
            });

        });
    }

    // screen elements extra js
    screen_DACB_elementsExtraJS = CarePass_BodyMeasurements_elementsExtraJS = function() {
        // screen (CarePass_BodyMeasurements) extra code

        /* mobilecollapsblock1_24 */

        $("#CarePass_BodyMeasurements_mobilecollapsblock1_24 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* ExternalMeasurements */

        listView = $("#CarePass_BodyMeasurements_ExternalMeasurements");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CarePass_BodyMeasurements_ExternalMeasurements .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem1_31 */

        /* mobilelistitem1_33 */

        /* mobilelistitem1_35 */

        /* mobilelistitem1_37 */

        /* mobilelistitem1_39 */

        /* mobilelistitem1_41 */

        /* mobilelistitem1_43 */

        /* mobilelistitem1_45 */

        /* mobilelistitem1_47 */

        /* mobilelistitem1_49 */

        /* mobilecollapsblock1_27 */

        $("#CarePass_BodyMeasurements_mobilecollapsblock1_27 .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* InternalMeasurements */

        listView = $("#CarePass_BodyMeasurements_InternalMeasurements");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CarePass_BodyMeasurements_InternalMeasurements .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem1_52 */

        /* mobilelistitem1_54 */

        /* mobilelistitem1_56 */

        /* mobilelistitem1_58 */

        /* mobilelistitem1_60 */

        /* mobilelistitem1_62 */

        /* mobilelistitem1_64 */

        /* mobilelistitem1_66 */

        /* mobilelistitem1_68 */

        /* mobilelistitem1_70 */

        /* mobilelistitem1_72 */

        /* mobilelistitem1_74 */

        /* mobilelistitem1_76 */

    }

    // screen elements handler
    screen_DACB_elementsEvents = CarePass_BodyMeasurements_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CarePass_BodyMeasurements_mobileheader [name="mobilenavbaritem4_12"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurements_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurements_mobileheader [name="mobilenavbaritem4_13"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_TimeLine', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_BodyMeasurements_mobilecontainer [name="ExternalMeasurements"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurementsType_Filter', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_BodyMeasurements_mobilecontainer [name="InternalMeasurements"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_BodyMeasurementsType_Filter', {
                        reverse: false
                    });

                }
            },
        });

        $('#CarePass_BodyMeasurements_mobilefooter1 [name="mobilenavbaritem4_7"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_All', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurements_mobilefooter1 [name="mobilenavbaritem4_8"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_New', {
                        reverse: false
                    });

                }
            },
        });
        $('#CarePass_BodyMeasurements_mobilefooter1 [name="mobilenavbaritem4_9"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('CarePass_Fitness_Activity_Filter', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#CarePass_BodyMeasurements").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CarePass_BodyMeasurements_beforeshow();
    });

    if (runBeforeShow) {
        CarePass_BodyMeasurements_beforeshow();
    } else {
        CarePass_BodyMeasurements_onLoad();
    }

}

$("#CarePass_BodyMeasurements").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CarePass_BodyMeasurements_js();
});