/*
 * JS for details generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

details_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'testid': 'details_testid',
        'mobilegrid_24': 'details_mobilegrid_24',
        'mobilegridcell_25': 'details_mobilegridcell_25',
        'mobilelabel_29': 'details_mobilelabel_29',
        'cpt': 'details_cpt',
        'mobilegridcell_26': 'details_mobilegridcell_26',
        'showname': 'details_showname',
        'mobilegrid_13': 'details_mobilegrid_13',
        'mobilegridcell_14': 'details_mobilegridcell_14',
        'showdosage': 'details_showdosage',
        'mobilegridcell_15': 'details_mobilegridcell_15',
        'mobilelabel_5': 'details_mobilelabel_5',
        'mobilegridcell_18': 'details_mobilegridcell_18',
        'mobilelabel_59': 'details_mobilelabel_59',
        'storeddosage': 'details_storeddosage',
        'cumulativedosage': 'details_cumulativedosage',
        'mobilegrid_42': 'details_mobilegrid_42',
        'mobilegridcell_43': 'details_mobilegridcell_43',
        'mobilegridcell_44': 'details_mobilegridcell_44',
        'mobilelabel_55': 'details_mobilelabel_55',
        'mobilegridcell_47': 'details_mobilegridcell_47',
        'mobilelabel_56': 'details_mobilelabel_56',
        'mobilegridcell_48': 'details_mobilegridcell_48',
        'mobilegridcell_49': 'details_mobilegridcell_49',
        'mobilegridcell_50': 'details_mobilegridcell_50',
        'mobilegridcell_51': 'details_mobilegridcell_51',
        'mobilegridcell_52': 'details_mobilegridcell_52',
        'mobilegridcell_53': 'details_mobilegridcell_53',
        'mobilelabel_58': 'details_mobilelabel_58',
        'mobilegridcell_54': 'details_mobilegridcell_54',
        'mobilelabel_57': 'details_mobilelabel_57',
        'mobileslider_6': 'details_mobileslider_6',
        'spacer_41': 'details_spacer_41',
        'mobilelabel_40': 'details_mobilelabel_40',
        'mobilelabel_34': 'details_mobilelabel_34',
        'mobileslider_35': 'details_mobileslider_35',
        'mobilelabel_32': 'details_mobilelabel_32',
        'mobileslider_30': 'details_mobileslider_30',
        'mobilelabel_33': 'details_mobilelabel_33',
        'mobileslider_31': 'details_mobileslider_31',
        'mobilelabel_36': 'details_mobilelabel_36',
        'mobileslider_37': 'details_mobileslider_37',
        'mobilegroupedbuttons_11': 'details_mobilegroupedbuttons_11',
        'mobilebutton_12': 'details_mobilebutton_12',
        'mobilebutton_10': 'details_mobilebutton_10'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'details';

    /*
     * Nonvisual components
     */
    var datasources = [];

    readtest = new Appery.DataSource(procedureDB_procedure_read_service, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("details");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['procedure'],
            'ID': 'showname',
            'ATTR': '@'
        }, {
            'PATH': ['dosage'],
            'ID': 'showdosage',
            'ATTR': '@'
        }, {
            'PATH': ['dosage'],
            'ID': 'mobileslider_6',
            'ATTR': 'value'
        }],
        'requestMapping': [{
            'PATH': ['X-Appery-Database-Id'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': '{database_id}'
        }, {
            'PATH': ['object_id'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': '_testid'
        }]
    });

    datasources.push(readtest);

    readtest2 = new Appery.DataSource(procedureDB_procedureCPT_read_service, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("details");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['procedure'],
            'ID': '___local_storage___',
            'ATTR': 'procedure'
        }, {
            'PATH': ['dosage'],
            'ID': '___local_storage___',
            'ATTR': 'dosage'
        }, {
            'PATH': ['CPT'],
            'ID': 'cpt',
            'ATTR': '@'
        }, {
            'PATH': ['CPT'],
            'ID': '___local_storage___',
            'ATTR': 'CPT'
        }],
        'requestMapping': [{
            'PATH': ['X-Appery-Database-Id'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': '{database_id}'
        }, {
            'PATH': ['object_id'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': '_testid'
        }]
    });

    datasources.push(readtest2);

    /*
     * Events and handlers
     */

    // Before Show
    details_beforeshow = function() {
        Appery.CurrentScreen = "details";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_8F3F_onLoad = details_onLoad = function() {
        screen_8F3F_elementsExtraJS();
        setText('details_testid', localStorage.getItem('_testid'));
        try {
            readtest.execute({})
        } catch (ex) {
            console.log(ex.name + '  ' + ex.message);
            hideSpinner();
        };
        var cumulative = $('[name=cumulativedosage]');
        cumulative.html('hic');
        var prevdosage = $('[name=showdosage]');
        prevdosage.html('hic');
        var setdosage = prevdosage.val();
        //cumulative.html(setdosage);  $('[name=showdosage]').value; //+$('[name=showdosage]').value;
        cumulative.val(setdosage);
        var input = $(".ui-slider-track.ui-mini");
        //input.css('height', '30px');
        //input.css('top', '-10px;');
        try {
            readtest2.execute({})
        } catch (ex) {
            console.log(ex.name + '  ' + ex.message);
            hideSpinner();
        };

        // TODO fire device events only if necessary (with JS logic)
        details_deviceEvents();
        details_windowEvents();
        screen_8F3F_elementsEvents();
    }

    // screen window events
    screen_8F3F_windowEvents = details_windowEvents = function() {

        $('#details').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    details_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_8F3F_elementsExtraJS = details_elementsExtraJS = function() {
        // screen (details) extra code

    }

    // screen elements handler
    screen_8F3F_elementsEvents = details_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#details_mobilecontainer [name="mobilebutton_10"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('cancer', {
                        reverse: false
                    });
                    setVar_('cumulativedosage', 'details_showdosage', 'text', '', this);

                }
            },
        });

    }

    $("#details").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        details_beforeshow();
    });

    if (runBeforeShow) {
        details_beforeshow();
    } else {
        details_onLoad();
    }

}

$("#details").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    details_js();
});