/*
 * JS for link generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '76c1243c-7c9f-4fcc-bd10-0ef35c0a1435';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CarePass_Login",
    "location": "CarePass_Login.html"
}, {
    "name": "body",
    "location": "body.html"
}, {
    "name": "CarePass_Fitness_Activity_All",
    "location": "CarePass_Fitness_Activity_All.html"
}, {
    "name": "Disclaimer",
    "location": "Disclaimer.html"
}, {
    "name": "CarePass_BodyMeasurements",
    "location": "CarePass_BodyMeasurements.html"
}, {
    "name": "CarePass_Fitness_Activity_New",
    "location": "CarePass_Fitness_Activity_New.html"
}, {
    "name": "CarePass_ErrorPopUp",
    "location": "CarePass_ErrorPopUp.html"
}, {
    "name": "CarePass_Fitness_Activity_Filter",
    "location": "CarePass_Fitness_Activity_Filter.html"
}, {
    "name": "CarePass_BodyMeasurements_New",
    "location": "CarePass_BodyMeasurements_New.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "map2",
    "location": "map2.html"
}, {
    "name": "CarePass_BodyMeasurementsType_Filter",
    "location": "CarePass_BodyMeasurementsType_Filter.html"
}, {
    "name": "CarePass_Fitness_Activity_TimeLine",
    "location": "CarePass_Fitness_Activity_TimeLine.html"
}, {
    "name": "map",
    "location": "map.html"
}, {
    "name": "CarePass_Chart",
    "location": "CarePass_Chart.html"
}, {
    "name": "CarePass_Fitness_Activity_Single",
    "location": "CarePass_Fitness_Activity_Single.html"
}, {
    "name": "action",
    "location": "action.html"
}, {
    "name": "load",
    "location": "load.html"
}, {
    "name": "cancer",
    "location": "cancer.html"
}, {
    "name": "tests",
    "location": "tests.html"
}, {
    "name": "start",
    "location": "start.html"
}, {
    "name": "CarePass_BodyMeasurements_Single",
    "location": "CarePass_BodyMeasurements_Single.html"
}, {
    "name": "link",
    "location": "link.html"
}];

link_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_51': 'link_mobilelabel_51',
        'procedure': 'link_procedure',
        'spacer_72': 'link_spacer_72',
        'mobilegroupedbuttons_47': 'link_mobilegroupedbuttons_47',
        'mobilebutton_48': 'link_mobilebutton_48',
        'mobilebutton_49': 'link_mobilebutton_49',
        'mobilebutton_50': 'link_mobilebutton_50',
        'mobilelist_54': 'link_mobilelist_54',
        'mobilelistitem_55': 'link_mobilelistitem_55',
        'mobilelistitembutton_56': 'link_mobilelistitembutton_56',
        'mobilelabel_67': 'link_mobilelabel_67',
        'mobilelabel_68': 'link_mobilelabel_68',
        'mobileimage_71': 'link_mobileimage_71',
        'mobilelistitem_57': 'link_mobilelistitem_57',
        'mobilelistitembutton_58': 'link_mobilelistitembutton_58',
        'mobilelabel_61': 'link_mobilelabel_61',
        'mobilelabel_53': 'link_mobilelabel_53',
        'mobileimage_66': 'link_mobileimage_66',
        'mobilelistitem_59': 'link_mobilelistitem_59',
        'mobilelistitembutton_60': 'link_mobilelistitembutton_60',
        'mobilelabel_62': 'link_mobilelabel_62',
        'mobilelabel_63': 'link_mobilelabel_63',
        'mobileimage_69': 'link_mobileimage_69',
        'youtube': 'link_youtube'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'link';

    /*
     * Nonvisual components
     */
    var datasources = [];

    restservice1 = new Appery.DataSource(procedureDB_link2_read_service, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("link");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['X-Appery-Database-Id'],
            'TYPE': 'STRING',
            'HEADER': true,
            'ATTR': '{database_id}'
        }]
    });

    datasources.push(restservice1);

    /*
     * Events and handlers
     */

    // Before Show
    link_beforeshow = function() {
        Appery.CurrentScreen = "link";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_9D86_onLoad = link_onLoad = function() {
        screen_9D86_elementsExtraJS();

        var video = Appery('youtube');

        $('<iframe />', {
            class: 'youtube-player',
            type: 'text/html',
            width: '300',
            height: '250',
            src: 'http://www.youtube.com/embed/wp-hH0eem-4',
            frameborder: '0'
        }).appendTo(video);

        $('<iframe />', {
            class: 'youtube-player',
            type: 'text/html',
            width: '300',
            height: '250',
            src: 'http://www.youtube.com/embed/LYCer0-GXFc',
            frameborder: '0'
        }).appendTo(video);

        $('<iframe />', {
            class: 'youtube-player',
            type: 'text/html',
            width: '300',
            height: '250',
            src: 'http://www.youtube.com/embed/On3Shdz5-0w',
            frameborder: '0'
        }).appendTo(video);

        var ifig = $(".imagefig");
        ifig.css('margin', 'auto');
        ifig.css('display', 'block');;
        setText('link_procedure', localStorage.getItem('procedure'));

        // TODO fire device events only if necessary (with JS logic)
        link_deviceEvents();
        link_windowEvents();
        screen_9D86_elementsEvents();
    }

    // screen window events
    screen_9D86_windowEvents = link_windowEvents = function() {

        $('#link').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    link_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_9D86_elementsExtraJS = link_elementsExtraJS = function() {
        // screen (link) extra code

        /* mobilelist_54 */

        listView = $("#link_mobilelist_54");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#link_mobilelist_54 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_55 */

        /* mobilelistitem_57 */

        /* mobilelistitem_59 */

    }

    // screen elements handler
    screen_9D86_elementsEvents = link_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

    }

    $("#link").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        link_beforeshow();
    });

    if (runBeforeShow) {
        link_beforeshow();
    } else {
        link_onLoad();
    }

}

$("#link").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    link_js();
});